### ISSUE TITLE
Deprecation when upgrade to Symfony 6.4

### ISSUE THREAD

**Issue by kseleznova-godaddy** [MySchoolManagement/elastic-apm-symfony-bundle#12]
I noticed the following deprecation report on my projects:

` Method "Symfony\Component\HttpKernel\Bundle\Bundle::boot()" might add "void" as a native return type declaration in the future. Do the same in child class "ElasticApmBundle\ElasticApmBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

Could you add this return type declaration?

**Comment by mfadul24** [comment]
Hi, I've fixed it on https://github.com/MySchoolManagement/elastic-apm-symfony-bundle/pull/11
But is waiting for approval since a few months.

**Comment by iainmckay** [comment]
Apologies for the delay, #11 has now been merged.
