### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by TNAJanssen** [MySchoolManagement/elastic-apm-symfony-bundle#5]
Hi,

Is php 8 support planned?

**Comment by iainmckay** [comment]
Yes, it's on our short-term road map but I don't have a concrete date.

**Comment by mfadul24** [comment]
Solved by https://github.com/MySchoolManagement/elastic-apm-symfony-bundle/pull/6

**Comment by iainmckay** [comment]
Support has been added in 1.0.3.
