### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by TNAJanssen** [MySchoolManagement/elastic-apm-symfony-bundle#8]
Hi,

Is support for Symfony 6 already planned?

Thanks!

**Comment by iainmckay** [comment]
Hi, yes we simply haven't upgraded our own app to 6 yet so are lagging behind here.

**Comment by Legion112** [comment]
Working on updating it to support 6 version.

**Comment by iainmckay** [comment]
#10 Was just merged.
